spring:
  application:
    name: payment-screenshot-processor-api
  data:
    mongodb:
      uri: mongodb+srv://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}/${DB_NAME}?retryWrites=true&w=majority&appName=${DB_HOST}

ocr:
  key: ${ocr.key}

api:
  key: ${api.key}