spring:
  application:
    name: payment-screenshot-processor-api
  data:
    mongodb:
      uri:  mongodb+srv://oliveraluis11:oliveraluis11@cluster-jayway.8mfmua4.mongodb.net/payment-screenshot-processor?retryWrites=true&w=majority&appName=cluster-jayway

ocr:
  key: ${ocr.key}

api:
  key: ${api.key}